# Generated by Django 3.2.9 on 2021-11-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.departament', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Mуж.', 'Муж.'), ('Жен.', 'Жен.')], max_length=4, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='programming_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.programminglanguage', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
    ]
